services:
  app:
    image: myapp:latest  # Your Java Spring Boot app image
    container_name: java_app
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    ports:
      - "8080:8080"  # Expose the app on port 8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx config
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
